version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: update Docker
          command: |
            docker version
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run: make docker
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              git config --global user.email "ci@gochain.io"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              make release
            fi
